### ISSUE TITLE
Amazing training metrics, but not good prediction

### ISSUE THREAD

**Issue by isabellameds** [pindi-krishna/Multiple-Sclerosis-Lesion-Segmentation#2]
Hi Krishna,

First of all, congratulations about the work! 
I am trying to use your code to create a model to predict the lesions using just T1 and FLAIR modalities, the training process achieves great metrics, but when I load the saved model to predict the images, the lesions are not well detected. For the prediction part, I resize and remove the null slices of the images in the same way you wrote in the data_preprocessing step. Do you have some suggestions about that?

Kind regards,
Isabella

**Comment by pindi-krishna** [comment]
Instead of using only the T1 and FLAIR modalities, please use all five which i mentioned in the paper. You may get good results then. Please let me know if it works.

**Comment by isabellameds** [comment]
Thank you for the reply!
